GET http://localhost:3001/try-qs?a[age]=20&a[name]=bill


###
POST http://localhost:3001/try-post
Content-Type: application/x-www-form-urlencoded

name=david&age=30

###
POST http://localhost:3001/try-post
Content-Type: application/json

{"name": "david" , "age" :30}